/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasEDevolucoesRouteImport } from './routes/trocas-e-devolucoes'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as TendenciasRouteImport } from './routes/tendencias'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as NossaHistoriaRouteImport } from './routes/nossa-historia'
import { Route as MaisVendidosRouteImport } from './routes/mais-vendidos'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as GuiaDeMedidasRouteImport } from './routes/guia-de-medidas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EntregaEFreteRouteImport } from './routes/entrega-e-frete'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as ClubeVipRouteImport } from './routes/clube-vip'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ContaRecuperarSenhaRouteImport } from './routes/conta.recuperar-senha'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as ContaLoginRouteImport } from './routes/conta.login'
import { Route as ContaEnderecosRouteImport } from './routes/conta.enderecos'
import { Route as ContaDadosRouteImport } from './routes/conta.dados'
import { Route as ContaCadastroRouteImport } from './routes/conta.cadastro'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'

const TrocasEDevolucoesRoute = TrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const NossaHistoriaRoute = NossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisVendidosRoute = MaisVendidosRouteImport.update({
  id: '/mais-vendidos',
  path: '/mais-vendidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeMedidasRoute = GuiaDeMedidasRouteImport.update({
  id: '/guia-de-medidas',
  path: '/guia-de-medidas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaEFreteRoute = EntregaEFreteRouteImport.update({
  id: '/entrega-e-frete',
  path: '/entrega-e-frete',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeVipRoute = ClubeVipRouteImport.update({
  id: '/clube-vip',
  path: '/clube-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRecuperarSenhaRoute = ContaRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaLoginRoute = ContaLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ContaRoute,
} as any)
const ContaEnderecosRoute = ContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaDadosRoute = ContaDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => ContaRoute,
} as any)
const ContaCadastroRoute = ContaCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => ContaRoute,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/clube-vip': typeof ClubeVipRoute
  '/colecoes': typeof ColecoesRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/entrega-e-frete': typeof EntregaEFreteRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/guia-de-medidas': typeof GuiaDeMedidasRoute
  '/lojas': typeof LojasRoute
  '/lookbook': typeof LookbookRoute
  '/mais-vendidos': typeof MaisVendidosRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tendencias': typeof TendenciasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/conta/cadastro': typeof ContaCadastroRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/login': typeof ContaLoginRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/recuperar-senha': typeof ContaRecuperarSenhaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/conta/': typeof ContaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/clube-vip': typeof ClubeVipRoute
  '/colecoes': typeof ColecoesRoute
  '/contato': typeof ContatoRoute
  '/entrega-e-frete': typeof EntregaEFreteRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/guia-de-medidas': typeof GuiaDeMedidasRoute
  '/lojas': typeof LojasRoute
  '/lookbook': typeof LookbookRoute
  '/mais-vendidos': typeof MaisVendidosRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tendencias': typeof TendenciasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/conta/cadastro': typeof ContaCadastroRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/login': typeof ContaLoginRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/recuperar-senha': typeof ContaRecuperarSenhaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/conta': typeof ContaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/clube-vip': typeof ClubeVipRoute
  '/colecoes': typeof ColecoesRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/entrega-e-frete': typeof EntregaEFreteRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/guia-de-medidas': typeof GuiaDeMedidasRoute
  '/lojas': typeof LojasRoute
  '/lookbook': typeof LookbookRoute
  '/mais-vendidos': typeof MaisVendidosRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tendencias': typeof TendenciasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/conta/cadastro': typeof ContaCadastroRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/login': typeof ContaLoginRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/recuperar-senha': typeof ContaRecuperarSenhaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/conta/': typeof ContaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/clube-vip'
    | '/colecoes'
    | '/conta'
    | '/contato'
    | '/entrega-e-frete'
    | '/faq'
    | '/favoritos'
    | '/guia-de-medidas'
    | '/lojas'
    | '/lookbook'
    | '/mais-vendidos'
    | '/nossa-historia'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tendencias'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/checkout/sucesso'
    | '/colecao/$slug'
    | '/conta/cadastro'
    | '/conta/dados'
    | '/conta/enderecos'
    | '/conta/login'
    | '/conta/pedidos'
    | '/conta/recuperar-senha'
    | '/produto/$slug'
    | '/conta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/clube-vip'
    | '/colecoes'
    | '/contato'
    | '/entrega-e-frete'
    | '/faq'
    | '/favoritos'
    | '/guia-de-medidas'
    | '/lojas'
    | '/lookbook'
    | '/mais-vendidos'
    | '/nossa-historia'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tendencias'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/checkout/sucesso'
    | '/colecao/$slug'
    | '/conta/cadastro'
    | '/conta/dados'
    | '/conta/enderecos'
    | '/conta/login'
    | '/conta/pedidos'
    | '/conta/recuperar-senha'
    | '/produto/$slug'
    | '/conta'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/carrinho'
    | '/clube-vip'
    | '/colecoes'
    | '/conta'
    | '/contato'
    | '/entrega-e-frete'
    | '/faq'
    | '/favoritos'
    | '/guia-de-medidas'
    | '/lojas'
    | '/lookbook'
    | '/mais-vendidos'
    | '/nossa-historia'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/tendencias'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/checkout/sucesso'
    | '/colecao/$slug'
    | '/conta/cadastro'
    | '/conta/dados'
    | '/conta/enderecos'
    | '/conta/login'
    | '/conta/pedidos'
    | '/conta/recuperar-senha'
    | '/produto/$slug'
    | '/conta/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ClubeVipRoute: typeof ClubeVipRoute
  ColecoesRoute: typeof ColecoesRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EntregaEFreteRoute: typeof EntregaEFreteRoute
  FaqRoute: typeof FaqRoute
  FavoritosRoute: typeof FavoritosRoute
  GuiaDeMedidasRoute: typeof GuiaDeMedidasRoute
  LojasRoute: typeof LojasRoute
  LookbookRoute: typeof LookbookRoute
  MaisVendidosRoute: typeof MaisVendidosRoute
  NossaHistoriaRoute: typeof NossaHistoriaRoute
  NovidadesRoute: typeof NovidadesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TendenciasRoute: typeof TendenciasRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TrocasEDevolucoesRoute: typeof TrocasEDevolucoesRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas-e-devolucoes': {
      id: '/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof TrocasEDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossa-historia': {
      id: '/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/nossa-historia'
      preLoaderRoute: typeof NossaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais-vendidos': {
      id: '/mais-vendidos'
      path: '/mais-vendidos'
      fullPath: '/mais-vendidos'
      preLoaderRoute: typeof MaisVendidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-medidas': {
      id: '/guia-de-medidas'
      path: '/guia-de-medidas'
      fullPath: '/guia-de-medidas'
      preLoaderRoute: typeof GuiaDeMedidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega-e-frete': {
      id: '/entrega-e-frete'
      path: '/entrega-e-frete'
      fullPath: '/entrega-e-frete'
      preLoaderRoute: typeof EntregaEFreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube-vip': {
      id: '/clube-vip'
      path: '/clube-vip'
      fullPath: '/clube-vip'
      preLoaderRoute: typeof ClubeVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/recuperar-senha': {
      id: '/conta/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/conta/recuperar-senha'
      preLoaderRoute: typeof ContaRecuperarSenhaRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/login': {
      id: '/conta/login'
      path: '/login'
      fullPath: '/conta/login'
      preLoaderRoute: typeof ContaLoginRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/enderecos': {
      id: '/conta/enderecos'
      path: '/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof ContaEnderecosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/dados': {
      id: '/conta/dados'
      path: '/dados'
      fullPath: '/conta/dados'
      preLoaderRoute: typeof ContaDadosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/cadastro': {
      id: '/conta/cadastro'
      path: '/cadastro'
      fullPath: '/conta/cadastro'
      preLoaderRoute: typeof ContaCadastroRouteImport
      parentRoute: typeof ContaRoute
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContaRouteChildren {
  ContaCadastroRoute: typeof ContaCadastroRoute
  ContaDadosRoute: typeof ContaDadosRoute
  ContaEnderecosRoute: typeof ContaEnderecosRoute
  ContaLoginRoute: typeof ContaLoginRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
  ContaRecuperarSenhaRoute: typeof ContaRecuperarSenhaRoute
  ContaIndexRoute: typeof ContaIndexRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaCadastroRoute: ContaCadastroRoute,
  ContaDadosRoute: ContaDadosRoute,
  ContaEnderecosRoute: ContaEnderecosRoute,
  ContaLoginRoute: ContaLoginRoute,
  ContaPedidosRoute: ContaPedidosRoute,
  ContaRecuperarSenhaRoute: ContaRecuperarSenhaRoute,
  ContaIndexRoute: ContaIndexRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  CarrinhoRoute: CarrinhoRoute,
  ClubeVipRoute: ClubeVipRoute,
  ColecoesRoute: ColecoesRoute,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EntregaEFreteRoute: EntregaEFreteRoute,
  FaqRoute: FaqRoute,
  FavoritosRoute: FavoritosRoute,
  GuiaDeMedidasRoute: GuiaDeMedidasRoute,
  LojasRoute: LojasRoute,
  LookbookRoute: LookbookRoute,
  MaisVendidosRoute: MaisVendidosRoute,
  NossaHistoriaRoute: NossaHistoriaRoute,
  NovidadesRoute: NovidadesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TendenciasRoute: TendenciasRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TrocasEDevolucoesRoute: TrocasEDevolucoesRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
